export const GET_APP_DATA = "GET_APP_DATA";
export const ERROR_RESPONSE_WITH_MESSAGE = "ERROR_RESPONSE_WITH_MESSAGE";
export const GET_LOADER_ERROR = "GET_LOADER_ERROR";

export const GET_THEME_SHOW_MORE_LOADER_SUCCESS = "GET_THEME_SHOW_MORE_LOADER_SUCCESS";
export const GET_WEB_FILTER_LOADER_SUCCESS = "GET_WEB_FILTER_LOADER_SUCCESS";


export const GET_THEME_ERROR_SUCCESS = "GET_THEME_ERROR_SUCCESS";
export const PLAN_LIMIT = 'PLAN_LIMIT'

export const SHOW_MORE_DATA_UPDATE = "SHOW_MORE_DATA_UPDATE";
export const FILTER_DATA_UPDATE = "FILTER_DATA_UPDATE";
export const SHOW_POP_UP = 'SHOW_POP_UP';
export const REPORT_MEDIA_POP_UP = 'REPORT_MEDIA_POP_UP';
export const REPORT_MEDIA_CLOSE_POP_UP = 'REPORT_MEDIA_CLOSE_POP_UP';
export const SHARE_POST_CLOSE_POP_UP = 'SHARE_POST_CLOSE_POP_UP';
export const CLOSE_POP_UP = 'CLOSE_POP_UP';
export const ONSITE_POPUP = "ONSITE_POPUP";
export const ONSITE_TOKEN_UPDATE = "ONSITE_TOKEN_UPDATE";
export const CLOSE_ONSITE_POPUP = "CLOSE_ONSITE_POPUP";
export const SHARE_POST_POP_UP = "SHARE_POST_POP_UP";
export const POST_DEFAULT_HEIGHT = "POST_DEFAULT_HEIGHT";


export const RENDER_ID = 'RENDER_ID';



// export const POST_POPUP = "POST_POPUP";
// export const CLOSE_POST_POPUP = "CLOSE_POST_POPUP";

